name: NPC
favicon: null
layout_spectrum: 0.41733746882528067
typography_spectrum: 0.8915427553001791
title: NPC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.23640820547007024
  lightness: 0.06652948004193604
  saturation: 0.7379292740952224
  rhythmicContrast: 0.9400586793199182
purpose: []
